### ISSUE TITLE
database configuration problems

### ISSUE THREAD

**Issue by CodelessFuture** [luckyframework/lucky_record#169] opened 2017-12-19 20:10 UTC
Hi. First try with Lucky Framework.

I configure postgres in config/database.cr as 

```crystal
database = "my_blog_#{Lucky::Env.name}"

LuckyRecord::Repo.configure do
  if Lucky::Env.production?
    settings.url = ENV.fetch("DATABASE_URL")
  else
    settings.url = LuckyRecord::PostgresURL.build(
      hostname: "localhost",
      database: database,
      username: "postgres",
      password: "postgres",
      port: "5432"
    )
  end
end

LuckyMigrator::Runner.configure do
  settings.database = database
end
```

but db was created and bin/setup ask password for max user (current user)

**Comment by paulcsmith** [comment] 2017-12-19 20:14
@CodelessFuture Thanks for giving Lucky a try, and for opening an issue. Could you also let me know what OS you are using? 

Also, you may be able to remove the username/password. What settings do you use for Rails/Phoenix/Node or whatever framework you currently use to connect to Postgres?

Thanks!

**Comment by CodelessFuture** [comment] 2017-12-19 20:17
I'm on last version mac os.

With all otterrete frameworks I use the credentials I set on database.cr

I try to puttana those because also if I omit those field it tries to use
max that is my current mac login user



Il 19/Dic/2017 21:14, "Paul Smith" <notifications@github.com> ha scritto:

**Comment by CodelessFuture** [comment] 2017-12-19 20:23
Sorry for T9 problems on last message

**Comment by CodelessFuture** [comment] 2017-12-19 20:28
```
max@iMac-di-Massimiliano  ~/Progetti/my_blog   master  cd ..
 max@iMac-di-Massimiliano  ~/Progetti  rm -rf my_blog
 max@iMac-di-Massimiliano  ~/Progetti  lucky init my_blog
Generating crystal project for my_blog
Adding Lucky dependencies to shards.yml
Done generating your Lucky project

  ▸ cd into my_blog
  ▸ run bin/setup
  ▸ run lucky dev to start the server
 max@iMac-di-Massimiliano  ~/Progetti  cd my_blog
 max@iMac-di-Massimiliano  ~/Progetti/my_blog   master  bin/setup

▸ Installing node dependencies
  yarn install v1.3.2
  info No lockfile found.
  [1/4] Resolving packages...
warning babel-brunch > babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
warning babel-brunch > babel-preset-latest > babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning babel-brunch > babel-preset-latest > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning babel-brunch > babel-preset-latest > babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning brunch > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
  [2/4] Fetching packages...
  [3/4] Linking dependencies...
warning " > postcss-cssnext@3.0.2" has unmet peer dependency "caniuse-lite@^1.0.30000697".
  [4/4] Building fresh packages...
  success Saved lockfile.
  Done in 82.05s.

▸ Compiling assets
  yarn run v1.3.2
  $ /Users/max/Progetti/my_blog/node_modules/.bin/brunch build
  21:27:29 - info: compiling
  21:27:30 - info: compiled 6 files into 2 files in 12.2 sec
  Done in 12.39s.

▸ Installing shards
  Updating https://github.com/luckyframework/lucky.git
  Updating https://github.com/luckyframework/lucky_cli.git
  Updating https://github.com/mosop/teeplate.git
  Updating https://github.com/luckyframework/habitat.git
  Updating https://github.com/luckyframework/lucky_inflector.git
  Updating https://github.com/luckyframework/lucky_record.git
  Updating https://github.com/kostya/blank.git
  Updating https://github.com/crystal-lang/crystal-db.git
  Updating https://github.com/will/crystal-pg.git
  Updating https://github.com/luckyframework/lucky_router.git
  Updating https://github.com/jwaldrip/shell-table.cr.git
  Updating https://github.com/luckyframework/lucky_migrator.git
  Installing lucky (0.6.3)
  Installing lucky_cli (0.7.1)
  Installing teeplate (0.4.5)
  Installing habitat (0.2.0)
  Installing lucky_inflector (HEAD)
  Installing lucky_record (0.3.1)
  Installing blank (HEAD)
  Installing db (0.4.3)
  Installing pg (0.13.4)
  Installing lucky_router (0.2.0)
  Installing shell-table (0.9.2)
  Installing lucky_migrator (0.3.0)

▸ Setting up the database
Password:
createdb: database creation failed: ERROR:  database "my_blog_development" already exists
  Done creating my_blog_development

▸ Migrating the database
 (DB::ConnectionRefused)
0x108196815: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1081967a1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x108196778: *CallStack::new:CallStack at ??
0x108194885: *raise<DB::ConnectionRefused>:NoReturn at ??
0x1082b8d79: *PG::Connection#initialize<DB::Database>:Bool at ??
0x1082b8bcb: *PG::Connection::new<DB::Database>:PG::Connection at ??
0x1082c8394: *PG::Driver#build_connection<DB::Database>:PG::Connection at ??
0x108192c43: ~procProc(DB::Connection)@lib/db/src/db/database.cr:50 at ??
0x1082bb94c: *DB::Pool(DB::Connection+)@DB::Pool(T)#build_resource:DB::Connection+ at ??
0x1082bb8d2: *DB::Pool(DB::Connection+)@DB::Pool(T)#initialize<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:Mutex at ??
0x10830dcec: *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) at ??
0x1082bb175: *DB::Database#initialize<DB::Driver+, URI>:DB::Pool(DB::Connection+) at ??
0x1082bafa7: *DB::Database::new<DB::Driver+, URI>:DB::Database at ??
0x108295ebd: *DB::build_database<URI>:DB::Database at ??
0x108295e91: *DB::build_database<String>:DB::Database at ??
0x1082e6db6: *LuckyMigrator::Runner#setup_migration_tracking_tables:DB::ExecResult at ??
0x1082e6f88: *LuckyMigrator::Runner#run_pending_migrations:Nil at ??
0x1082e437f: *Db::Migrate#call:Nil at ??
0x1082ddf32: *LuckyCli::Runner::run<Array(String)>:Nil at ??
0x1082ddb0d: *LuckyCli::Runner::run:Nil at ??
0x108175017: __crystal_main at ??
0x10818b318: main at ??

▸ All done. Run 'lucky dev' to start the app
```

**Comment by CodelessFuture** [comment] 2017-12-19 20:31
If I omit confit it ask for user password for db creation, then  fails to work on db migration (not present). Instead if I configure as above, it ask me for password (accept that of max - current user) and don't give error on migration, but the db was created as user max

**Comment by CodelessFuture** [comment] 2017-12-19 20:39
Sorry I don't see I don't drop the db after previous installation

This is the new bin/setup after I dropped it:

```
 Setting up the database
Password:
  Done creating my_blog_development

▸ Migrating the database
 (DB::ConnectionRefused)
0x10f455815: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10f4557a1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10f455778: *CallStack::new:CallStack at ??
0x10f453885: *raise<DB::ConnectionRefused>:NoReturn at ??
0x10f577d79: *PG::Connection#initialize<DB::Database>:Bool at ??
0x10f577bcb: *PG::Connection::new<DB::Database>:PG::Connection at ??
0x10f587394: *PG::Driver#build_connection<DB::Database>:PG::Connection at ??
0x10f451c43: ~procProc(DB::Connection)@lib/db/src/db/database.cr:50 at ??
0x10f57a94c: *DB::Pool(DB::Connection+)@DB::Pool(T)#build_resource:DB::Connection+ at ??
0x10f57a8d2: *DB::Pool(DB::Connection+)@DB::Pool(T)#initialize<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:Mutex at ??
0x10f5cccec: *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) at ??
0x10f57a175: *DB::Database#initialize<DB::Driver+, URI>:DB::Pool(DB::Connection+) at ??
0x10f579fa7: *DB::Database::new<DB::Driver+, URI>:DB::Database at ??
0x10f554ebd: *DB::build_database<URI>:DB::Database at ??
0x10f554e91: *DB::build_database<String>:DB::Database at ??
0x10f5a5db6: *LuckyMigrator::Runner#setup_migration_tracking_tables:DB::ExecResult at ??
0x10f5a5f88: *LuckyMigrator::Runner#run_pending_migrations:Nil at ??
0x10f5a337f: *Db::Migrate#call:Nil at ??
0x10f59cf32: *LuckyCli::Runner::run<Array(String)>:Nil at ??
0x10f59cb0d: *LuckyCli::Runner::run:Nil at ??
0x10f434017: __crystal_main at ??
0x10f44a318: main at ??

▸ All done. Run 'lucky dev' to start the app
```

So create db but same error for migrations

**Comment by CodelessFuture** [comment] 2017-12-20 21:18
▸ Setting up the database
  "postgres://postgres:postgres@localhost/my_blog_development"
Password: **HERE I HAVE TO PUT max Postgres user password or fail to authenticate**
  Done creating my_blog_development

▸ Migrating the database
  "postgres://postgres:postgres@localhost/my_blog_development"
  Did nothing. No pending migrations.

```crystal
database = "my_blog_#{Lucky::Env.name}"

LuckyRecord::Repo.configure do
  if Lucky::Env.production?
    settings.url = ENV.fetch("DATABASE_URL")
  else
    settings.url = LuckyRecord::PostgresURL.build(
      hostname: "localhost",
      database: database,
      username: "postgres",
      password: "postgres"
    )
    p LuckyRecord::PostgresURL.build(
      hostname: "localhost",
      database: database,
      username: "postgres",
      password: "postgres"
    )
  end
end

LuckyMigrator::Runner.configure do
  settings.database = database
end
```

**Comment by paulcsmith** [comment] 2017-12-20 21:19
Can you try username: postgres but with remove the password?

**Comment by CodelessFuture** [comment] 2017-12-20 21:23
▸ Setting up the database
  "postgres://postgres@localhost/my_blog_development"
Password: **TRY POSTGRES PASSWORD AND FAIL**
Password: **max password is good again**
  Done creating my_blog_development

▸ Migrating the database
  "postgres://postgres@localhost/my_blog_development"
 (DB::ConnectionRefused)
0x10a2f4035: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10a2f3fc1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10a2f3f98: *CallStack::new:CallStack at ??
0x10a2f20a5: *raise<DB::ConnectionRefused>:NoReturn at ??
0x10a416649: *PG::Connection#initialize<DB::Database>:Bool at ??
0x10a41649b: *PG::Connection::new<DB::Database>:PG::Connection at ??
0x10a425c64: *PG::Driver#build_connection<DB::Database>:PG::Connection at ??
0x10a2f0463: ~procProc(DB::Connection)@lib/db/src/db/database.cr:50 at ??
0x10a41921c: *DB::Pool(DB::Connection+)@DB::Pool(T)#build_resource:DB::Connection+ at ??
0x10a4191a2: *DB::Pool(DB::Connection+)@DB::Pool(T)#initialize<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:Mutex at ??
0x10a46f4fc: *DB::Pool(T)::new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay<Int32, Int32, Int32, Float64, Int32, Float64, &Proc(DB::Connection+)>:DB::Pool(DB::Connection+) at ??
0x10a418a45: *DB::Database#initialize<DB::Driver+, URI>:DB::Pool(DB::Connection+) at ??
0x10a418877: *DB::Database::new<DB::Driver+, URI>:DB::Database at ??
0x10a3f378d: *DB::build_database<URI>:DB::Database at ??
0x10a3f3761: *DB::build_database<String>:DB::Database at ??
0x10a4485c6: *LuckyMigrator::Runner#setup_migration_tracking_tables:DB::ExecResult at ??
0x10a448798: *LuckyMigrator::Runner#run_pending_migrations:Nil at ??
0x10a441c4f: *Db::Migrate#call:Nil at ??
0x10a43b802: *LuckyCli::Runner::run<Array(String)>:Nil at ??
0x10a43b3dd: *LuckyCli::Runner::run:Nil at ??
0x10a2d25f2: __crystal_main at ??
0x10a2e8918: main at ??

**Comment by CodelessFuture** [comment] 2017-12-20 21:31
To me, it seems that only with all parameters set it pass without errors the creation and migrations steps, what I don't understand is  why it search for a postgres user named as my Mac user name. I use postgres with Laravel, Elixir, Lapis, Adonis and Amber without problems

**Comment by paulcsmith** [comment] 2017-12-20 21:32
@CodelessFuture Which database are you using with Amber. Is it Crecto? If so I can take a look at how they build URLs. I think LuckyRecord is the same, but maybe they're doing something slightly different

**Comment by CodelessFuture** [comment] 2017-12-20 21:35
I use Granite

**Comment by paulcsmith** [comment] 2017-12-20 21:37
It seems Granite does not build a URL for you. If you use the URL you use for Granite, but in LuckyRecord, does it let you connect and migrate?

**Comment by CodelessFuture** [comment] 2017-12-20 21:39
Actually on my iMac I don't have a project in Amber. But I'm sure on any framework I use the same credentials

**Comment by paulcsmith** [comment] 2017-12-20 21:41
Ah, if you're not using Amber on the computer that is having trouble, maybe try building the URL and setting it directly (don't use LuckyRecord to build the URL):

"postgres://username:password@hostname:5432/#{database_name}"

And you may want to try connecting with the URL from the command line to make sure the URL can for sure connect. This would help determine if it is the URL or some other connection issue

**Comment by paulcsmith** [comment] 2017-12-20 21:56
BTW, to check that the URL is correct, use `psql <URL>`. You probably already knew, but posting just in case: So I think it would look like this `psql postgres://<username>:<password>@hostname:5432/my_blog_development`

If that works with `pswl`, but the same URL `settings.url = "postgres://<username>:<password>@hostname:5432/my_blog_development"` doesn't work in LuckyRecord, LMK

**Comment by CodelessFuture** [comment] 2017-12-21 07:01
As expected:

**max@iMac-di-Massimiliano > ~ >** psql postgres://postgres:postgres@localhost:5432/my_blog_development
psql (10.1)
Type "help" for help.

my_blog_development=#

**Comment by CodelessFuture** [comment] 2017-12-21 07:10
I used:

`crystal
settings.url = "postgres://postgres:postgres@localhost:5432/my_blog_development"
`
In the database.cr

But:

▸ Setting up the database
Password: **(Postgres user max password only work)**
  
Done creating my_blog_development

▸ Migrating the database
  Did nothing. No pending migrations.

▸ All done. Run 'lucky dev' to start the app

**Comment by oneiros** [comment] 2017-12-21 09:41
@CodelessFuture Are you sure that PostgreSQL is listening on TCP port 5432 and if yes, that your user is allowed to authenticate over TCP?

On my machine I connect via UNIX sockets, in which case `localhost:5432` may not appear in the URL.

So you could try something like

    settings.url = "postgres://postgres:postgres@/my_blog_development"

Also, if the PostgreSQL authentication method for connections via UNIX sockets is configured to be one of `trust`, `ident` or `peer` you might even need to omit the username and / or password.

**Comment by CodelessFuture** [comment] 2017-12-21 09:51
> @CodelessFuture Are you sure that PostgreSQL is listening on TCP port 5432 and if yes, that your user is allowed to authenticate over TCP?

Have you read what I posted a couple of comment above?

```
max@iMac-di-Massimiliano > ~ > psql postgres://postgres:postgres@localhost:5432/my_blog_development
psql (10.1)
Type "help" for help.

my_blog_development=#
```

By the way I try also what you propose, but with same result.....

**Comment by oneiros** [comment] 2017-12-21 15:22
> @oneiros Have you read what I posted a couple of comment above?

Yes, but by then my first sentence was already written. Sorry, connecting via TCP obviously works.

I still think further investigating the authentication settings in pg_hba.conf might be worthwile, though. I remember back when I mostly used MySQL, this used to give me a lot of headaches.

PostgreSQL allows setting different authentication methods depending on the type of connection and the user/role that tries to connect. So your postgres user might be allowed to connect via UNIX socket (local) using peer authentication (meaning you need to be the system user postgres), while your max user can only connect via TCP using a password (which is stored in postgresql and may be different from your system user max's password).

I am not on a mac btw, so it might be helpful to know, how you installed PostgreSQL. Postgres.app for instance seems to create a postgres user with the name of your system user but no password.

One last thing: Since the DB was created with the max user and you seem to be able to connect with this user and a password, could you not use this user's credentials instead of the postgres user? I guess you have tried that already, but I want to cover all bases just to be sure.

**Comment by CodelessFuture** [comment] 2017-12-21 15:56
I go ahead with max for now, and in the next days I try on linux

**Comment by paulcsmith** [comment] 2017-12-21 16:02
@CodelessFuture I'm glad it works with max and your password. If you're concerned about committing your creds to a repo, you can add `*.local.cr` to your `.gitignore` file. Then add a `config/database.local.cr` which will be gitignored. Then you can set the URL there without worrying about committing your credentials:

```crystal
LuckyRecord::Report.configure do
  unless Lucky::Env.production?
    settings.url = # .... build the URL for you local Postgres env
  end
end
```

Note that this will be added to .gitignore by default in the next version to make local config easy

**Comment by patleb** [comment] 2018-01-10 05:42
First try here also. `settings.url` isn't used to connect to postgres, it falls back to default user session options. I haven't dig to find the cause, but I thought you should know that `bin/setup` isn't helping for trying the framework. (even setting DATABASE_URL isn't working)

**Comment by paulcsmith** [comment] 2018-01-10 14:51
@CodelessFuture I think this is still an issue, so I'll re-open this. But if the email noise is too much (which I totally understand) there is an unsubscribe button in the top right column of the page

**Comment by patleb** [comment] 2018-01-10 16:00
@paulcsmith this what I did. Which suggests that settings in `database.cr` aren't the one used to connect to the database.

**Comment by paulcsmith** [comment] 2018-01-10 16:09
@patleb Oh I see. I misunderstood your original comment. I'm assuming `lucky db.create` works, but `lucky db.migrate` fails with ConnectionRefused?

If so can you add this in your tasks.cr file (before `LuckyCli::Runner.run`):

```crystal
p LuckyRecord::Repo.settings.url
```

That will print the URL that is being used by LuckyRecord. It *should* match what you put in `config/database.cr`

**Comment by patleb** [comment] 2018-01-10 16:30
No, `lucky db.create` doesn't work, the database configurations aren't the one set by `LuckyRecord::Repo.settings.url`. Sure, the output is the same as what is set in `database.cr`, but it is the default local user settings that are used if any. The connection error message is:
```
createdb: could not connect to database template1: FATAL:  role "plebel" does not exist
```
Which shows that the username, password and database configurations are ignored.
Sorry, normally, I would just dig and find where the bug is, but I just wanted to try the framework out of curiosity. I cannot help more than that for this issue.

**Comment by paulcsmith** [comment] 2018-01-10 17:03
Looks like we need to parse the postgres URL and pass the host, port, username, password to `createdb` if present.

Here is how a node package parses the string: https://github.com/iceddev/pg-connection-string/blob/master/index.js

Here are the options `createdb` takes: https://www.postgresql.org/docs/9.1/static/app-createdb.html There are examples near the bottom.

@mikeeus If you have some time, do you think you could tackle this one? If not that's ok! I can work on it later this week.

**Comment by t-richards** [comment] 2018-04-24 16:54
Just bumped into this issue.

>Looks like we need to parse the postgres URL and pass the host, port, username, password to `createdb`

I briefly dug into Rails to see how it handles this situation, and it looks like they do exactly this. They set these values as environment variables, which are then respected by the `createdb` command.

https://www.postgresql.org/docs/current/static/libpq-envars.html

The following workaround seems to resolve this issue for me:

```
$ lucky db.create
createdb: could not connect to database template1: FATAL:  role "tom" does not exist

$ export PGUSER=postgres    # postgres is my superuser role
$ lucky db.create
Done creating foo_development

```

**Comment by paulcsmith** [comment] 2018-04-24 17:47
@t-richards Thanks for chiming in that's definitely helpful. I believe the issue should be fixed by the latest this PR in LuckyMigrator: https://github.com/luckyframework/lucky_migrator/pull/74

In your shard.yml you can remove `version: "xxx"` and instead use `branch: master` and then run `shards update`. That will give you the latest changes. If you try `lucky db.create` with that (and the correct settings in `config/database.cr` you should be good to go. 

If you have time could you give that a try and post back here with results? If it works I'll go ahead and close this issue

**Comment by paulcsmith** [comment] 2018-05-22 12:44
The new releases are out and should fix this issue. Please comment or open an issue if you run into the same problem.

**Closed by paulcsmith** 2018-05-22 12:44 UTC
